#!/usr/bin/bash

export GOPATH="$PWD"

go install networking
go install ordercontroller
go install drivers
go install misc
go install elevator
go build

if [ -f elevator.log ]; then
    rm elevator.log
fi

touch elevator.log
